using EmployeeCommon;
using HiringCompany.DatabaseAccess;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.ServiceModel;
using System.Text;
using System.Threading.Tasks;
using System.Timers;
using ICommon;
using HiringCompany.Logger;

[assembly: log4net.Config.XmlConfigurator(Watch = true)]

namespace HiringCompany.Services
{

    [ServiceBehavior(InstanceContextMode = InstanceContextMode.Single,
      ConcurrencyMode = ConcurrencyMode.Reentrant)]
    public class EmployeeService : IEmployeeService
    {

        private HiringCompanyDB hiringCompanyDB = HiringCompanyDB.Instance();
        private OutsorcingCompProxy outsorcingProxy;
        private System.Timers.Timer lateOnJobTimer = new System.Timers.Timer();

        public EmployeeService()
        {
            lateOnJobTimer.Elapsed += new ElapsedEventHandler(NotifyOnLate);
            lateOnJobTimer.Interval = 15000;
            //lateOnJobTimer.Enabled = true;
        }

        // slanje maila onima koji nisu online, srediti ovu metodu body i content od maila...
        // i srediti raspored kad se ovo ukljucuje i iskljucuje i slicno
        /*ideja: kad se pokrene servis izvuku se sati dolazaka svih klijenata,
         *  i izracuna se sat najkasnijeg dolaska, i kad prodje taj sat vise nema potrebe da se vrti onaj timer*/
        private void NotifyOnLate(object sender, ElapsedEventArgs e)
        {
            StringBuilder messageToLog = new StringBuilder();
            messageToLog.AppendLine(string.Format("Method: EmployeeService.NotifyOnLate()"));

            string _senderEmailAddress = "mzftn123fakultet@gmail.com"; // i ovo cuvati u nekom fajlu
            string _senderPassword = "miljanazvezdana123";
            Console.WriteLine("alarm...");
            foreach (Employee em in hiringCompanyDB.AllEmployees)
            {
                if (!hiringCompanyDB.OnlineEmployees.Contains(em))
                {
                    DateTime current = DateTime.Now;
                    DateTime workTimeEmployee = new DateTime(current.Year, current.Month, current.Day, em.StartHour, em.StartMinute, 0);
                    TimeSpan timeDiff = current - workTimeEmployee;
                    TimeSpan allowed = new TimeSpan(0, 15, 0);

                    if (timeDiff > allowed)
                    {
                        var client = new SmtpClient("smtp.gmail.com", 587)
                        {
                            Credentials = new NetworkCredential(_senderEmailAddress, _senderPassword),
                            EnableSsl = true
                        };
                        client.Send(_senderEmailAddress, em.Email, "Obavestenje", "Zakasnili ste na posao!");
                    }
                }
            }

            messageToLog.AppendLine("finished successfully.");
            Program.Logger.Info(messageToLog);
        }


        /*ovde treba korisniku da posaljemo sve notifikacije koje su stigle za njega dok nije bio online.
         da li da napravimo listu stringova - notifikacije, u klijentu, pa da ih iscitavamo preko employees,
         ili skroz novu tabelu, key je autogenerated number, imamo property string username, i property string notification?
         mislim da je prvi pristup logicniji..? mozda bi trebali da imamo klasu notification koja sadrzi text, timestamp, i da znamo za koga je?
         ali ne moze da bude samo jedno polje za koga je posto moze biti za vise. onda jedino da klasa employee ima List<Notification>... 
          */

        public bool SignIn(string username, string password)
        {
            StringBuilder messageToLog = new StringBuilder();
            messageToLog.AppendLine(string.Format("Method: EmployeeService.SignIn(), " +
                                              "params: string username={0}, string password={0}", username, password));

            Employee employee = hiringCompanyDB.GetEmployee(username);

            if (employee != null && password.Equals(employee.Password))
            {
                IEmployeeServiceCallback callbackClient = OperationContext.Current.GetCallbackChannel<IEmployeeServiceCallback>();

                // Console.WriteLine(( (IClientChannel)callbackClient ).State.ToString());
                ICommunicationObject cObject = callbackClient as ICommunicationObject;
                if (cObject != null)
                {
                    IEmployeeServiceCallback outCallback;
                    if (!hiringCompanyDB.ConnectionChannelsClients.TryGetValue(username, out outCallback))
                    {
                        hiringCompanyDB.ConnectionChannelsClients.Add(username, callbackClient);

                        lock (hiringCompanyDB.OnlineEmployees_lock)
                        {
                            hiringCompanyDB.OnlineEmployees.Add(employee);
                            messageToLog.AppendLine("finished successfully.");
                        }

                        using (Notifier notifier = new Notifier())
                        {
                            notifier.SyncAll();
                        }

                    }
                    else
                    {
                        messageToLog.AppendLine("Channel associated with username already exists.");
                        // taj kanal vec postoji, tj. nije izbrisan iz ConnectionChannelsClients,
                        // iako klijent svaki put kad se loguje pravi novi kanal, nesto nije u redu...
                        // mozda ovde da uradimo remove starog kanala, i sacuvamo novi?
                        // i da proverimo da li je vec dodati u online Employees 
                    }
                }

            }
            else
            {
                messageToLog.AppendLine("Employee equals null, or password was wrong.");
                messageToLog.AppendLine("returned false");
                return false;
            }

            messageToLog.AppendLine("returned true");
            Program.Logger.Info(messageToLog);
            return true;
        }

        public void SignOut(string username)
        {
            StringBuilder messageToLog = new StringBuilder();
            messageToLog.AppendLine(string.Format("Method: EmployeeService.SignOut(), " +
                                              "params: string username={0}", username));


            lock (hiringCompanyDB.OnlineEmployees_lock)
            {
                Employee em = hiringCompanyDB.OnlineEmployees.Find(e => e.Username.Equals(username));
                if (em != null)
                {
                    hiringCompanyDB.OnlineEmployees.Remove(em);
                    hiringCompanyDB.ConnectionChannelsClients.Remove(username);
                    messageToLog.AppendLine("finished successfully.");
                }
                else
                {
                    messageToLog.AppendLine("employee does not exist.");
                }
            }

            using (Notifier notifier = new Notifier())
            {
                notifier.SyncAll();
            }

            Program.Logger.Info(messageToLog);
        }

        public void ChangeEmployeeData(string username, string name, string surname, string email, string password)
        {
            StringBuilder messageToLog = new StringBuilder();
            messageToLog.AppendLine(string.Format("Method: EmployeeService.ChangeEmployeeData(), " +
                                              "params: string username={0}, string name={1}," +
                                                  " string surname={2}, string email={3}, string password={4}",
                                                  username, name, surname, email, password));

            try
            {
                using (var access = new AccessDB())
                {
                    Employee em = access.Employees.SingleOrDefault(e => e.Username.Equals(username));

                    if (em != null)
                    {
                        em.Name = name != "" ? name : em.Name;
                        em.Surname = surname != "" ? surname : em.Surname;
                        em.Email = email != "" ? email : em.Email;
                        em.Password = password != "" ? password : em.Password;
                        access.SaveChanges();
                        messageToLog.AppendLine("updated employee data in .mdf database.");
                    }
                }
            }
            catch (DbEntityValidationException e)
            {
                foreach (var eve in e.EntityValidationErrors)
                {
                    messageToLog.AppendLine(string.Format("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                        eve.Entry.Entity.GetType().Name, eve.Entry.State));
                    foreach (var ve in eve.ValidationErrors)
                    {
                        messageToLog.AppendLine(string.Format("- Property: \"{0}\", Value: \"{1}\", Error: \"{2}\"",
                            ve.PropertyName,
                            eve.Entry.CurrentValues.GetValue<object>(ve.PropertyName),
                            ve.ErrorMessage));
                    }
                }
            }

            lock (hiringCompanyDB.OnlineEmployees_lock)
            {
                Employee em = hiringCompanyDB.OnlineEmployees.Find(e => e.Username.Equals(username));
                if (em != null)
                {
                    em.Name = name != "" ? name : em.Name;
                    em.Surname = surname != "" ? surname : em.Surname;
                    em.Email = email != "" ? email : em.Email;
                    em.Password = password != "" ? password : em.Password;
                    messageToLog.AppendLine("updated employee data in OnlineEmployees list.");
                }
            }

            using (Notifier notifier = new Notifier())
            {
                notifier.SyncAll();
            }

            Program.Logger.Info(messageToLog);
        }

        public void SetWorkingHours(string username, int beginH, int beginM, int endH, int endM)
        {
            StringBuilder messageToLog = new StringBuilder();
            messageToLog.AppendLine(string.Format("Method: EmployeeService.SetWorkingHours(), " +
                                              "params: string username={0}, int beginH={1}, int beginM={2}," +
                                                  "int endH={3}, int endM={4}", username, beginH, beginM, endH, endM));

            try
            {
                using (var access = new AccessDB())
                {
                    Employee em = access.Employees.SingleOrDefault(e => e.Username.Equals(username));
                    if (em != null)
                    {
                        em.StartHour = beginH;
                        em.StartMinute = beginM;
                        em.EndHour = endH;
                        em.EndMinute = endM;
                        access.SaveChanges();
                        messageToLog.AppendLine("updated working hours data in .mdf database.");
                    }
                }
            }
            catch (DbEntityValidationException e)
            {
                foreach (var eve in e.EntityValidationErrors)
                {
                    messageToLog.AppendLine(string.Format("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                        eve.Entry.Entity.GetType().Name, eve.Entry.State));
                    foreach (var ve in eve.ValidationErrors)
                    {
                        messageToLog.AppendLine(string.Format("- Property: \"{0}\", Value: \"{1}\", Error: \"{2}\"",
                            ve.PropertyName,
                            eve.Entry.CurrentValues.GetValue<object>(ve.PropertyName),
                            ve.ErrorMessage));
                    }
                }
            }

            lock (hiringCompanyDB.OnlineEmployees_lock)
            {
                Employee em = hiringCompanyDB.OnlineEmployees.Find(e => e.Username.Equals(username));
                if (em != null)
                {
                    em.StartHour = beginH;
                    em.StartMinute = beginM;
                    em.EndHour = endH;
                    em.EndMinute = endM;
                    messageToLog.AppendLine("updated working hours data in OnlineEmployees list.");
                }
            }

            using (Notifier notifier = new Notifier())
            {
                notifier.SyncAll();
            }

            messageToLog.AppendLine("returned.");
            Program.Logger.Info(messageToLog);
        }

        public void AskForPartnership(string outsorcingCompanyName)
        {
            StringBuilder messageToLog = new StringBuilder();
            messageToLog.AppendLine(string.Format("Method: EmployeeService.AskForPartnership(), " +
                                              "params: string outsorcingCompanuName={0}", outsorcingCompanyName));

            //ovde namestiti da iz baze-mape, ili iz nekog konfig fajla iscitamo adresu te kompanije

            string outsorcingSvcEndpoint = string.Format("net.tcp://{0}/OutsourcingService", hiringCompanyDB.PartnerCompaniesAddresses[outsorcingCompanyName]);

            NetTcpBinding binding = new NetTcpBinding();
            binding.OpenTimeout = new TimeSpan(1, 0, 0);
            binding.CloseTimeout = new TimeSpan(1, 0, 0);
            binding.SendTimeout = new TimeSpan(1, 0, 0);
            binding.ReceiveTimeout = new TimeSpan(1, 0, 0);

            EndpointAddress endpointAddress = new EndpointAddress(new Uri(outsorcingSvcEndpoint));


            // izbrisati iz liste, i dodati ako negde nesto treba
            // i onda kasnije kad pozivamo neke motede uvek proveravmao da li smo partneri
            using (outsorcingProxy = new OutsorcingCompProxy(binding, endpointAddress))
            {
                outsorcingProxy.AskForPartnership(hiringCompanyDB.CompanyName);
                messageToLog.AppendLine("called method for sending partnership request on OutsorcingCompProxy successfully.");
            }

            Program.Logger.Info(messageToLog);
        }

        public bool AddNewEmployee(Employee em)
        {
            StringBuilder messageToLog = new StringBuilder();
            messageToLog.AppendLine(string.Format("Method: bool EmployeeService.AddNewEmployee(), Employee.Username={0}",em.Username));

            bool retVal = hiringCompanyDB.AddNewEmployee(em);

            using (Notifier notifier = new Notifier())
            {
                notifier.SyncAll();
            }

            messageToLog.AppendLine(string.Format("returned {0}.", retVal));
            Program.Logger.Info(messageToLog);

            return retVal;
        }

        public void ChangeEmployeeType(string username, EmployeeType type)
        {
            StringBuilder messageToLog = new StringBuilder();
            messageToLog.AppendLine(string.Format("Method: EmployeeService.ChangeEmployeeType(), " +
                                              "params: string username={0}, string EmployeeType={0}", username, type.ToString()));

            try
            {
                using (var access = new AccessDB())
                {
                    Employee em = access.Employees.SingleOrDefault(e => e.Username.Equals(username));
                    if (em != null)
                    {
                        em.Type = type;
                        access.SaveChanges();
                        messageToLog.AppendLine("employee type changed in .mdf database.");
                    }
                }
            }
            catch (DbEntityValidationException e)
            {
                foreach (var eve in e.EntityValidationErrors)
                {
                    messageToLog.AppendLine(string.Format("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                        eve.Entry.Entity.GetType().Name, eve.Entry.State));
                    foreach (var ve in eve.ValidationErrors)
                    {
                        messageToLog.AppendLine(string.Format("- Property: \"{0}\", Value: \"{1}\", Error: \"{2}\"",
                            ve.PropertyName,
                            eve.Entry.CurrentValues.GetValue<object>(ve.PropertyName),
                            ve.ErrorMessage));
                    }
                }
            }

            lock (hiringCompanyDB.OnlineEmployees_lock)
            {
                Employee em = hiringCompanyDB.OnlineEmployees.Find(e => e.Username.Equals(username));
                if (em != null)
                {
                    em.Type = type;
                    messageToLog.AppendLine("employee type changed in OnlineEmployees list");
                }
            }

            using (Notifier notifier = new Notifier())
            {
                notifier.SyncAll();
            }
            Program.Logger.Info(messageToLog);
        }

        public void SendApprovedUserStories(string projectName, List<UserStory> userStories)
        {
            StringBuilder messageToLog = new StringBuilder();
            messageToLog.AppendLine(string.Format("Method: EmployeeService.SendApprovedUserStories(), " +
                                              "params: string projectName={0};  userStories.Count={1}", projectName,userStories.Count));
            Project proj = new Project();
            try
            {
                using (var access = new AccessDB())
                {
                    proj = access.Projects.Include("UserStories").SingleOrDefault(p => p.Name.Equals(projectName));

                    if (proj != null)
                    {
                        int i = 0;
                        if (proj.UserStories.Count == userStories.Count)
                        {
                            for (; i < proj.UserStories.Count; i++)
                            {
                                // ovde cu staviti log samo za debuging
                                string dbBeforeChange = string.Format("dbBeforeChange: proj.UserStories[i].IsApprovedByPo={0}.{1}.{2}", proj.Name, proj.UserStories[i].Title, proj.UserStories[i].IsApprovedByPO);
                                string receivedUserStory = string.Format("receivedUserStory: userStories[i].IsApprovedByPo={0}.{1}", userStories[i].Title, userStories[i].IsApprovedByPO);

                                proj.UserStories[i].IsApprovedByPO = userStories[i].IsApprovedByPO;

                                string dbAfterChange = string.Format("dbAfterChange: proj.UserStories[i].IsApprovedByPo={0}.{1}.{2}", proj.Name, proj.UserStories[i].Title, proj.UserStories[i].IsApprovedByPO);

                                messageToLog.AppendLine(dbBeforeChange);
                                messageToLog.AppendLine(receivedUserStory);
                                messageToLog.AppendLine(dbAfterChange);
                            }
                        }
                        else
                        {
                            messageToLog.AppendLine("Unsuccessful idea! :( ");
                        }

                        access.SaveChanges();

                        messageToLog.AppendLine("changed user stories data in .mdf database.");
                    }
                }
            }
            catch (DbEntityValidationException e)
            {
                foreach (var eve in e.EntityValidationErrors)
                {
                    messageToLog.AppendLine(string.Format("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                        eve.Entry.Entity.GetType().Name, eve.Entry.State));
                    foreach (var ve in eve.ValidationErrors)
                    {
                        messageToLog.AppendLine(string.Format("- Property: \"{0}\", Value: \"{1}\", Error: \"{2}\"",
                            ve.PropertyName,
                            eve.Entry.CurrentValues.GetValue<object>(ve.PropertyName),
                            ve.ErrorMessage));
                    }
                }
            }

            string outsorcingSvcEndpoint = string.Format("net.tcp://{0}/OutsourcingService", hiringCompanyDB.PartnerCompaniesAddresses[proj.OutsourcingCompany]);

            NetTcpBinding binding = new NetTcpBinding();
            binding.OpenTimeout = new TimeSpan(1, 0, 0);
            binding.CloseTimeout = new TimeSpan(1, 0, 0);
            binding.SendTimeout = new TimeSpan(1, 0, 0);
            binding.ReceiveTimeout = new TimeSpan(1, 0, 0);

            EndpointAddress endpointAddress = new EndpointAddress(new Uri(outsorcingSvcEndpoint));

            List<UserStoryCommon> userStoriesForSend = new List<UserStoryCommon>();
            foreach (var us in userStories)
            {
                userStoriesForSend.Add(new UserStoryCommon(us.Title, us.Description, us.AcceptanceCriteria, us.IsApprovedByPO));
            }

            // kada sve treba da proverimo da li smo partneri i ostalo?

            using (outsorcingProxy = new OutsorcingCompProxy(binding, endpointAddress))
            {
                outsorcingProxy.SendEvaluatedUserstoriesToOutsourcingCompany(userStoriesForSend, projectName);
                messageToLog.AppendLine("called method for sending approved user stories on OutsorcingCompProxy successfully.");
            }

            try
            {
                using (var access = new AccessDB())
                {
                    // o ovome porazmisliti da li radimo dobro, procitati na linku sve
                    // https://msdn.microsoft.com/en-us/library/jj574232(v=vs.113).aspx

                    proj.UserStories.RemoveAll(us => us.IsApprovedByPO == false);
                    access.SaveChanges();

                    messageToLog.AppendLine("Removed user stories that were not approved in .mdf database."); 

                    //var Projects = access.Projects.Include("UserStories");
                    //var project = from pr in access.Projects
                    //              where pr.Name.Equals(proj.Name)
                    //              select pr;

                    //if (project != null)
                    //{

                    //    project.UserStories.RemoveRange(project.UserStories.Where(u => u.IsApprovedByPO == false));
                    //    //7var us = access.userstories.First(u => u.IsApprovedByPO == false )

                    //    //access.userstories.Remove()

                    //    access.SaveChanges();
                    //}
                }
            }
            catch (DbEntityValidationException e)
            {
                foreach (var eve in e.EntityValidationErrors)
                {
                    messageToLog.AppendLine(string.Format("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                        eve.Entry.Entity.GetType().Name, eve.Entry.State));
                    foreach (var ve in eve.ValidationErrors)
                    {
                        messageToLog.AppendLine(string.Format("- Property: \"{0}\", Value: \"{1}\", Error: \"{2}\"",
                            ve.PropertyName,
                            eve.Entry.CurrentValues.GetValue<object>(ve.PropertyName),
                            ve.ErrorMessage));
                    }
                }
            }

            using (Notifier notifier = new Notifier())
            {
                notifier.SyncAll();               
            }

        }

        public void CreateNewProject(Project p)
        {
            StringBuilder messageToLog = new StringBuilder();
            messageToLog.AppendLine(string.Format("Method: EmployeeService.CreateNewProject(), Project.Name={0}", p.Name));

            hiringCompanyDB.AddNewProject(p); // lockovanje? bolje raditi interno u AddNewProjet metodi, kad smo je vec napravili

            // odrediti velicinu notifikacija otprilike, zbog size text blocka
            string notification = string.Format("Project <{0}> is waiting for approval. Description: {1}", p.Name,p.Description); 

            using (Notifier notifier = new Notifier())
            {
                notifier.SyncSpecialClients(EmployeeType.CEO, notification);
            }

            messageToLog.AppendLine("finished successfully.");
            Program.Logger.Info(messageToLog);
        }

        public void ProjectApprovedByCeo(Project p)
        {
            StringBuilder messageToLog = new StringBuilder();
            messageToLog.AppendLine(string.Format("Method: EmployeeService.ProjectApprovedByCeo(), Project.Name={0}", p.Name));

            try
            {
                using (var access = new AccessDB())
                {
                    var project = from proj in access.Projects
                                  where proj.Name.Equals(p.Name)
                                  select proj;

                    var pr = project.ToList().FirstOrDefault();
                    pr.IsAcceptedCEO = true;
                    access.SaveChanges();

                    messageToLog.AppendLine("project propertu IsAcceptedCEO updated in .mdf database.");
                }
            }
            catch (DbEntityValidationException e)
            {
                foreach (var eve in e.EntityValidationErrors)
                {
                    messageToLog.AppendLine(string.Format("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                        eve.Entry.Entity.GetType().Name, eve.Entry.State));
                    foreach (var ve in eve.ValidationErrors)
                    {
                        messageToLog.AppendLine(string.Format("- Property: \"{0}\", Value: \"{1}\", Error: \"{2}\"",
                            ve.PropertyName,
                            eve.Entry.CurrentValues.GetValue<object>(ve.PropertyName),
                            ve.ErrorMessage));
                    }
                }
            }

            string notification = string.Format("Project {0} is approved. Description: {1}", p.Name, p.Description);
            using (Notifier notifier = new Notifier())
            {
                notifier.SyncAll();
                notifier.NotifySpecialClient(p.ProductOwner, notification);
            }

            messageToLog.AppendLine("finished successfully.");
            Program.Logger.Info(messageToLog);
        }

        public void SendProject(string outscCompany, Project p)
        {
            // ovde prvo treba da proverimo da li smo partneri!!!!!!!!!!!!!!!!!! ?

            StringBuilder messageToLog = new StringBuilder();
            messageToLog.AppendLine(string.Format("Method: EmployeeService.SendProject(), " +
                                              "params: string outscCompany={0}, Project.Name={1}", outscCompany, p.Name));


            ProjectCommon proj = new ProjectCommon(p.Name, p.Description, p.StartDate, p.Deadline);

            
            // potom namestiti da iz baze-mape, ili fajla iscitamo adresu te kompanije

            string outsorcingSvcEndpoint = string.Format("net.tcp://{0}/OutsourcingService", hiringCompanyDB.PartnerCompaniesAddresses[outscCompany]);

            NetTcpBinding binding = new NetTcpBinding();
            binding.OpenTimeout = new TimeSpan(1, 0, 0);
            binding.CloseTimeout = new TimeSpan(1, 0, 0);
            binding.SendTimeout = new TimeSpan(1, 0, 0);
            binding.ReceiveTimeout = new TimeSpan(1, 0, 0);

            EndpointAddress endpointAddress = new EndpointAddress(new Uri(outsorcingSvcEndpoint));


            using (outsorcingProxy = new OutsorcingCompProxy(binding, endpointAddress))
            {
                outsorcingProxy.SendProjectToOutsourcingCompany(hiringCompanyDB.CompanyName, proj);
                messageToLog.AppendLine("called method for sending project on OutsorcingCompProxy successfully.");
            }

            Program.Logger.Info(messageToLog);
        }
    }
}
